/** Static mirror of the reviewed domain-audit catalog; never derived from input. */
export const AUDIT_CATALOG = {
  "site_settings.updated": "site_settings",
  "map_theme.created": "map_theme",
  "map_theme.updated": "map_theme",
  "map_theme.deleted": "map_theme",
  "legal_policy.created": "legal_policy",
  "legal_policy.updated": "legal_policy",
  "legal_policy.deleted": "legal_policy",
  "file.created": "file",
  "file.updated": "file",
  "file.deleted": "file",
  "file_folder.created": "file_folder",
  "file_folder.updated": "file_folder",
  "file_folder.deleted": "file_folder",
  "category.created": "category",
  "category.updated": "category",
  "category.deleted": "category",
  "tag.created": "tag",
  "tag.updated": "tag",
  "tag.deleted": "tag",
  "genre.created": "genre",
  "genre.updated": "genre",
  "genre.deleted": "genre",
  "style.created": "style",
  "style.updated": "style",
  "style.deleted": "style",
  "format.created": "format",
  "format.updated": "format",
  "format.deleted": "format",
  "client.created": "client",
  "client.updated": "client",
  "client.deleted": "client",
  "map_place.created": "map_place",
  "map_place.updated": "map_place",
  "map_place.deleted": "map_place",
  "audience_segment.created": "audience_segment",
  "audience_segment.updated": "audience_segment",
  "menu.created": "menu",
  "menu.updated": "menu",
  "menu.deleted": "menu",
  "mail_adapter.created": "mail_adapter",
  "mail_adapter.updated": "mail_adapter",
  "mail_adapter.deleted": "mail_adapter",
  "email_suppression.updated": "email_suppression",
  "translation_settings.updated": "translation_settings",
  "translation_provider.created": "translation_provider",
  "translation_provider.updated": "translation_provider",
  "translation_provider.deleted": "translation_provider",
  "member.updated": "member",
  "member_tag.created": "member_tag",
  "member_tag.deleted": "member_tag",
  "artist.created": "artist",
  "artist.updated": "artist",
  "artist.deleted": "artist",
  "label.created": "label",
  "label.updated": "label",
  "label.deleted": "label",
  "post_series.created": "post_series",
  "post_series.updated": "post_series",
  "post_series.deleted": "post_series",
  "program_event_type.created": "program_event_type",
  "program_event_type.updated": "program_event_type",
  "program_event_type.deleted": "program_event_type",
  "program_event.created": "program_event",
  "program_event.updated": "program_event",
  "program_event.deleted": "program_event",
  "program_event_series.created": "program_event_series",
  "program_event_series.updated": "program_event_series",
  "program_event_series.deleted": "program_event_series",
  "release.created": "release",
  "release.updated": "release",
  "release.deleted": "release",
  "campaign.created": "campaign",
  "campaign.updated": "campaign",
  "campaign.deleted": "campaign",
  "email_template.created": "email_template",
  "email_template.updated": "email_template",
  "email_template.deleted": "email_template",
  "email_layout.created": "email_layout",
  "email_layout.updated": "email_layout",
  "email_layout.deleted": "email_layout",
  "email_event_mapping.updated": "email_event_mapping",
  "form.created": "form",
  "form.updated": "form",
  "form.deleted": "form",
  "form_submission.created": "form_submission",
  "form_submission.deleted": "form_submission",
  "post.created": "post",
  "post.updated": "post",
  "post.deleted": "post",
  "page.created": "page",
  "page.updated": "page",
  "page.deleted": "page",
  "work.created": "work",
  "work.updated": "work",
  "work.deleted": "work",
  "account.updated": "account",
  "account.deleted": "account",
} as const;

export type AuditAction = keyof typeof AUDIT_CATALOG;
export const AUDIT_ACTIONS = Object.keys(
  AUDIT_CATALOG,
) as readonly AuditAction[];

export function requireCatalogTarget(
  action: AuditAction,
  targetType: string,
  targetId: string,
): void {
  if (AUDIT_CATALOG[action] !== targetType || targetId === "")
    throw new TypeError(
      `audit action ${action} requires target_type ${AUDIT_CATALOG[action]} and target_id`,
    );
}
